#!/bin/bash
#Menu
echo -e "========================================================"
echo -e "==================DevGracyy Solution===================™"
echo -e "========================================================"
echo -e "* menu      : Show Menu"
echo -e "* usernew   : Create OVPN & SSH Account"
echo -e "* trial     : Make Trial Account"
echo -e "* delete    : Delete User Account"
echo -e "* check     : Check the logged account"
echo -e "* member    : Show OVPN & SSH Account"
echo -e "* dagjr     : Restart all services(WEB,SSH,DB,OVPN)"
echo -e "* reboot    : Reboot the system or VPS"
echo -e "* speedtest : Speedtest"
echo -e "* info      : Info about the server"
echo -e "* about     : DevGracyy Solution™"
echo -e "========================================================"
echo -e "========================================================"
echo -e "========================================================"
